### ISSUE TITLE
1.18  1.19?

### ISSUE THREAD

**Issue by Adogs1** [MrTransistorsChannel/SandDupe#2]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Minecraft server version and type (e.g. official 1.17.1,Paper build-###, etc):**

**Additional context**

**Comment by MrTransistorsChannel** [comment]
The plugin works on 1.18.2 and 1.19.2 without updating

**Comment by Adogs1** [comment]
> 该插件适用于1.18.2和1.19.2，无需更新

Thank you very much!
